abbr -a v 'nvim'
abbr -a npmi 'npm i'
abbr -a npmig 'npm i -g'
abbr -a npmis 'npm i -S'
abbr -a npmisd 'npm i -D'
abbr -a npmu 'npm un'
abbr -a npmus 'npm un -S'
abbr -a npmusd 'npm un -D'
abbr -a npmug 'npm un -g'
abbr -a bri 'brew install'
abbr -a bru 'brew uninstall'
abbr -a gr 'git grep'
abbr -a gri 'git grep -i'
abbr -a gril 'git grep -il'
abbr -a grl 'git grep -l'
abbr -a gco 'git checkout'
abbr -a gb 'git blame'
abbr -a gsh 'git show'

abbr -a g 'git status' 
abbr -a gst 'git stash' 
abbr -a gstp 'git stash pop' 
abbr -a gpr 'git pull --rebase' 
abbr -a gpsh 'git push' 
abbr -a gd 'git diff' 
abbr -a gl 'git log' 
abbr -a glp 'git log -p' 
abbr -a gf 'git fetch' 
abbr -a gcof 'git checkout -f' 
abbr -a gcm 'git commit -m' 
abbr -a gca 'git commit -am' 
abbr -a gbr 'git branch' 

abbr -a rld 'source ~/.config/fish/config.fish' 
