abbr v nvim
abbr s subl
abbr npmi 'npm i'
abbr npmig 'npm i -g'
abbr npmis 'npm i --save'
abbr npmisd 'npm i --save-dev'
abbr npmu 'npm un'
abbr npmus 'npm un --save'
abbr npmusd 'npm un --save-dev'
abbr npmug 'npm un -g'
abbr bri 'brew install'
abbr bru 'brew uninstall'
abbr gr 'git grep'
abbr gri 'git grep -i'
abbr gril 'git grep -il'
abbr grl 'git grep -l'
abbr gco 'git checkout'
abbr gb 'git blame'
abbr gsh 'git show'
